import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'David',
      email: 'admin@example.com',
      password: bcrypt.hashSync('Ecplace2022*'),
      isAdmin: true,
    },
    {
      name: 'Roberto',
      email: 'user@example.com',
      password: bcrypt.hashSync('Ecplace2022*'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Time Teller Nixon Watch',
      slug: 'time-teller-nixon-watch',
      category: 'Fashion',
      image: '/images/A045-000.jpg',
      isFeatured: true,
      featuredImage: '/images/banner1.jpg',
      price: 144,
      brand: 'Nixon',
      rating: 5.0,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular watch',
    },
    {
      name: 'Re Run Nixon Watch',
      slug: 're-run-nixon-watch',
      category: 'Fashion',
      image: '/images/A158-300.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 180,
      brand: 'Nixon',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular watch',
    },
    {
      name: 'Regulus Nixon Watch',
      slug: 'regulus-nixon-watch',
      category: 'Fashion',
      image: '/images/A1180-001.jpg',
      price: 203,
      brand: 'Nixon',
      rating: 4.0,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular watch',
    },
    {
      name: 'Belt Hydra Fitletic',
      slug: 'belt-hydra-fitletic',
      category: 'Sports',
      image: '/images/HD08-C2.jpg',
      price: 100,
      brand: 'Fitletic',
      rating: 4.8,
      numReviews: 10,
      countInStock: 20,
      description: 'Sports belt for hydration',
    },
    {
      name: 'Hydra Palm Fitletic',
      slug: 'hydra-palm-fitletic',
      category: 'Sports',
      image: '/images/HH12P-09.jpg',
      price: 45,
      brand: 'Fitletic',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Sports bottle for hydration',
    },
    {
      name: 'HydRun Vest Fitletic',
      slug: 'hydrun-vest-fitletic',
      category: 'Sports',
      image: '/images/HV16-01L.jpg',
      price: 169,
      brand: 'Fitletic',
      rating: 3.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Sports backpack',
    },
    {
      name: 'Harris vessels, Set of 3 Arteriors',
      slug: 'harris-vessels-set-of-3-met-arteriors',
      category: 'Home',
      image: '/images/2945.jpg',
      price: 1238,
      brand: 'Arteriors',
      rating: 4.9,
      numReviews: 10,
      countInStock: 20,
      description: 'One Each, Polished Brass',
    },
    {
      name: 'Ryan Vase Arterios',
      slug: 'ryan-vase-arteriors',
      category: 'Home',
      image: '/images/4703.jpg',
      price: 732,
      brand: 'Arteriors',
      rating: 4.7,
      numReviews: 10,
      countInStock: 20,
      description: 'Antique Brass',
    },
    {
      name: 'Shepard Lamp Arteriors',
      slug: 'shepard-lamp-arteriors',
      category: 'Home',
      image: '/images/4790.jpg',
      price: 593,
      brand: 'Arteriors',
      rating: 4.3,
      numReviews: 10,
      countInStock: 20,
      description: 'Vintage Bronze, Antique Brass',
    },
  ],
};
export default data;
